<a href="https://colab.research.google.com/github/noeyxos/python/blob/master/Python08_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#   Numpy(넘파이)


#   C언어로 개발된 파이썬에서 과학적 계산을 위한 핵심 라이브러리. 다차원 배열 객체와 배열과 함께 작동하는 도구들을 제공한다. 
#   하지만 고수준의 데이터 분석기능을 제공하지는 않기 때문에 NUMPY 배열과 함께 Pandas와 같은 도구를 함께 사용한다.

In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])   #numpy배열 만들기
print(arr)                  #기본 배열보다 속도도 빠르고 여러 장점이 많다.
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
# zeros, ones, empty를 사용해서 배열을 생성한다.
car = np.zeros((3,3))
print(car)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
np.empty((4,4))

array([[2.61510527e-316, 0.00000000e+000, 4.78108711e+180,
        9.93259671e+247],
       [1.03542810e+208, 2.31833744e-152, 1.05996355e-153,
        1.17365078e+214],
       [6.01347002e-154, 8.88254272e+247, 2.43395944e-152,
        8.03704345e-095],
       [6.32266889e+180, 1.45517163e-152, 3.06250721e+257,
        1.27966001e-152]])

In [11]:
# 특정 범위의 변수를 생성할 때 arange()를 사용한다.
print(np.arange(10))        #10개(갯수)
print(np.arange(1,10))      #(초기값, 끝점)
print(np.arange(1,10,2))    #(초기값, 끝점, 증가값)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [18]:
#ndarray 배열의 모양, 차수, 데이터 타입 확인해보기
arr = np.array([[1,2,3],[4,5,6]])     #[]의 개수로 차원을 알 수 있다. 
print(arr)                            #2x3배열

[[1 2 3]
 [4 5 6]]


In [19]:
# 차원의 확인
arr.ndim

2

In [20]:
# 데이터의 모양을 확인하는 방법
arr.shape

(2, 3)

In [22]:
# 데이터 타입의 확인
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [24]:
# ndarray 배열의 타입 변환
arr_int = np.array([1,2,3,4])
print(arr_int.dtype)
arr_float = arr_int.astype(np.float64)    #int64인데이터 타입을 float64로 변환
print(arr_float.dtype)

int64
float64


In [26]:
arr_str = np.array(['1','2','3','4'])
print(arr_str.dtype)
arr_int = arr_str.astype(np.int64)
print(arr_int)

<U1
[1 2 3 4]


In [28]:
# 배열의 연산
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [30]:
print(np.add(arr1,arr2))
print(np.multiply(arr1,arr2))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [31]:
#ndarray 배열 슬라이싱 하기
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [33]:
arr_1 = arr[:2,1:3]   #:2 는 배열의 요소, 1:3은 배열 안을 슬라이싱
print(arr_1)

[[2 3]
 [5 6]]


In [36]:
# 3 을 출력해보기
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0,2]

3

In [40]:
arr = np.array ([[1,2,3],[4,5,6]])
idx = arr > 3     # 조건 
print(idx)        # 결과

[[False False False]
 [ True  True  True]]


In [41]:
arr[idx]    #true 인 값만 출력 (조건에 대한 결과만 출력하기)

array([4, 5, 6])

In [50]:
#csv파일 읽기
redwine = np.loadtxt(fname = 'winequality-red.csv', delimiter=';', skiprows=1)    #fname: 파일이름 delimeter:구별자 skiprow : 건너뛸 열

In [51]:
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [57]:
# 기초 통계 함수
# sum   합계
# mean  평균
# std   표준편차 
# var   분산  (std의 제곱)
# min   최솟값
# max   최댓값

In [60]:
print(redwine.sum())
print(redwine.sum(axis=0))    #첫번째 세로축으로 합계를 내는 것 
print(redwine.mean(axis=0))   #첫번째 세로축으로 평균을 구함

152084.78194
[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [63]:
print(redwine[:]) 

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [64]:
print(redwine[:,0]) 

[7.4 7.8 7.8 ... 6.3 5.9 6. ]


In [65]:
print(redwine[:,0].mean()) 

8.31963727329581


In [67]:
print(redwine.max(axis=0)) 
print(redwine.min(axis=0)) 

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]
[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]
